"""upgrade reviews

Revision ID: 068e5e61aef7
Revises: 0c07853ba3f9
Create Date: 2024-01-18 12:24:12.476243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068e5e61aef7'
down_revision: Union[str, None] = '0c07853ba3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NetworksReviews', sa.Column('text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NetworksReviews', 'text')
    # ### end Alembic commands ###
