"""delete users

Revision ID: b4ccf277c49b
Revises: d255c9cdfbae
Create Date: 2024-01-16 21:32:40.004115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ccf277c49b'
down_revision: Union[str, None] = 'd255c9cdfbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('Users')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
