"""Create tags and networks

Revision ID: d255c9cdfbae
Revises: d2706dd85a8a
Create Date: 2024-01-16 20:21:16.006297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd255c9cdfbae'
down_revision: Union[str, None] = 'd2706dd85a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('descriptionResult', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('TagsToNetworks',
    sa.Column('id_network', sa.Integer(), nullable=False),
    sa.Column('id_tags', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_network'], ['Networks.id'], ),
    sa.ForeignKeyConstraint(['id_tags'], ['Tags.id'], ),
    sa.PrimaryKeyConstraint('id_network', 'id_tags')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TagsToNetworks')
    op.drop_table('Tags')
    op.drop_table('Networks')
    # ### end Alembic commands ###
