"""add filed image

Revision ID: fae6a5570fe2
Revises: b4ccf277c49b
Create Date: 2024-01-17 14:12:51.273076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae6a5570fe2'
down_revision: Union[str, None] = 'b4ccf277c49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Networks', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Networks', 'image')
    # ### end Alembic commands ###
